import React, { useState } from "react";
import { Info } from "lucide-react";

interface GalleryItem {
  id: number;
  image: string;
  title: string;
  description: string;
  category: string;
}

const Gallery: React.FC = () => {
  const galleryItems: GalleryItem[] = [
    {
      id: 1,
      image:
        "https://images.pexels.com/photos/6771985/pexels-photo-6771985.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Training Loss Curve",
      description:
        "Visualization of model training performance showing convergence over epochs",
      category: "Model Training",
    },
    {
      id: 2,
      image:
        "https://images.pexels.com/photos/7567434/pexels-photo-7567434.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Buy/Sell Signal Chart",
      description:
        "Stock price chart with overlaid buy and sell signals generated by the LSTM model",
      category: "Prediction Results",
    },
    {
      id: 3,
      image:
        "https://images.pexels.com/photos/7567440/pexels-photo-7567440.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Dashboard UI Mockup",
      description:
        "User interface design for the stock prediction dashboard with real-time analytics",
      category: "UI Design",
    },
    {
      id: 4,
      image:
        "https://images.pexels.com/photos/7567538/pexels-photo-7567538.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Model Architecture Diagram",
      description:
        "Visual representation of the LSTM neural network architecture used in the project",
      category: "Technical Design",
    },
    {
      id: 5,
      image:
        "https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Feature Importance Plot",
      description:
        "Visualization showing the relative importance of different features in the prediction model",
      category: "Data Analysis",
    },
    {
      id: 6,
      image:
        "https://images.pexels.com/photos/7567473/pexels-photo-7567473.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Mobile App Prototype",
      description:
        "Interactive prototype of the mobile application for on-the-go stock predictions",
      category: "UI Design",
    },
  ];

  const [activeCategory, setActiveCategory] = useState<string>("All");
  const categories = [
    "All",
    ...Array.from(new Set(galleryItems.map((item) => item.category))),
  ];

  const filteredItems =
    activeCategory === "All"
      ? galleryItems
      : galleryItems.filter((item) => item.category === activeCategory);

  return (
    <section id="gallery" className="py-24 bg-white dark:bg-charcoal">
      <div className="container mx-auto px-6">
        <h2 className="font-sans font-bold text-3xl md:text-4xl mb-6 text-center text-deepBlue dark:text-white">
          Visual Results & UI Mockups
        </h2>

        <p className="text-gray-600 dark:text-gray-300 text-lg max-w-3xl mx-auto text-center mb-12">
          Explore visualizations of our model performance, prediction results,
          and interface designs
        </p>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-3 mb-12">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`py-2 px-4 rounded-full text-sm font-medium transition-all duration-300 ${
                activeCategory === category
                  ? "bg-deepBlue text-white"
                  : "bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700"
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredItems.map((item) => (
            <div
              key={item.id}
              className="group relative rounded-lg overflow-hidden shadow-lg bg-white dark:bg-gray-800"
            >
              <div className="aspect-w-16 aspect-h-9 w-full">
                <img
                  src={item.image}
                  alt={item.title}
                  className="w-full h-64 object-cover transition-transform duration-500 group-hover:scale-110"
                />
              </div>

              {/* Hover Overlay */}
              <div className="absolute inset-0 bg-deepBlue bg-opacity-80 flex flex-col justify-end p-6 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <div className="flex items-center gap-2 mb-2">
                  <Info className="w-5 h-5 text-white" />
                  <h3 className="font-sans font-bold text-xl text-white">
                    {item.title}
                  </h3>
                </div>
                <p className="text-white text-sm">{item.description}</p>
                <span className="mt-3 inline-block px-3 py-1 bg-white bg-opacity-20 rounded-full text-xs text-white">
                  {item.category}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Gallery;
